twig:
  default_path: "%kernel.project_dir%/templates"
  paths:
    "%kernel.project_dir%/vendor/knplabs/knp-paginator-bundle/templates": KnpPaginator
    "%kernel.project_dir%/public/assets/images": images
    # '%kernel.project_dir%/vendor/knplabs/knp-paginator-bundle/templates': KnpPaginator
    "%kernel.project_dir%/public/css": css
    "%kernel.project_dir%/public/img": img
