vich_uploader:
  db_driver: orm

  mappings:
    produitPlace:
      uri_prefix: /img/product
      upload_destination: "%kernel.project_dir%/public/img/product"
    marketPlace:
      uri_prefix: /img/markets
      upload_destination: "%kernel.project_dir%/public/img/markets"
    categoriePlace:
      uri_prefix: /img/categories
      upload_destination: "%kernel.project_dir%/public/img/categories"
    typeLivraisonPlace:
      uri_prefix: /img/TypeLivraison
      upload_destination: "%kernel.project_dir%/public/img/TypeLivraison"

    blogsPlace:
      uri_prefix: /img/blog
      upload_destination: "%kernel.project_dir%/public/img/blog"
